-- Seed 3 story templates (Block 05)
INSERT INTO public.templates (id, name, version, age_bands, config) VALUES
(
  'a0000000-0000-0000-0000-000000000001',
  'adventure',
  1,
  ARRAY['4-6', '7-9'],
  '{"theme":"adventure","supporting_characters":[{"role":"guide","description":"friendly animal companion"}],"beats":[{"beat_id":"setup_1","act":"setup","page_index":1,"narrative_summary":"Child discovers a magical world","illustration_instructions":"Child standing in magical forest, curious expression"},{"beat_id":"setup_2","act":"setup","page_index":2,"narrative_summary":"Child meets a friendly guide","illustration_instructions":"Child with friendly animal companion"},{"beat_id":"mission_1","act":"mission","page_index":3,"narrative_summary":"The guide explains the mission","illustration_instructions":"Child listening intently"},{"beat_id":"mission_2","act":"mission","page_index":4,"narrative_summary":"Child sets off on the adventure","illustration_instructions":"Child walking bravely"},{"beat_id":"challenge_1","act":"challenge","page_index":5,"narrative_summary":"Child faces the first challenge","illustration_instructions":"Child at challenge, determined"},{"beat_id":"challenge_2","act":"challenge","page_index":6,"narrative_summary":"Child uses clever thinking","illustration_instructions":"Child thinking, lightbulb moment"},{"beat_id":"challenge_3","act":"challenge","page_index":7,"narrative_summary":"Child overcomes the obstacle","illustration_instructions":"Child victorious"},{"beat_id":"resolution_1","act":"resolution","page_index":8,"narrative_summary":"Child completes the mission","illustration_instructions":"Child celebrating"},{"beat_id":"resolution_2","act":"resolution","page_index":9,"narrative_summary":"Child says goodbye to new friends","illustration_instructions":"Child waving goodbye"},{"beat_id":"reflection_1","act":"reflection","page_index":10,"narrative_summary":"Child returns home with memories","illustration_instructions":"Child at home, reflective"}]}'::jsonb
),
(
  'a0000000-0000-0000-0000-000000000002',
  'exploration',
  1,
  ARRAY['4-6', '7-9'],
  '{"theme":"exploration","supporting_characters":[{"role":"mentor","description":"wise explorer"}],"beats":[{"beat_id":"setup_1","act":"setup","page_index":1,"narrative_summary":"Child finds a mysterious map","illustration_instructions":"Child holding old map, excited"},{"beat_id":"setup_2","act":"setup","page_index":2,"narrative_summary":"Child meets a wise explorer","illustration_instructions":"Child with mentor figure"},{"beat_id":"mission_1","act":"mission","page_index":3,"narrative_summary":"The map leads to a hidden place","illustration_instructions":"Child studying map"},{"beat_id":"mission_2","act":"mission","page_index":4,"narrative_summary":"Child begins the journey","illustration_instructions":"Child starting journey"},{"beat_id":"challenge_1","act":"challenge","page_index":5,"narrative_summary":"Child discovers a hidden cave","illustration_instructions":"Child at cave entrance"},{"beat_id":"challenge_2","act":"challenge","page_index":6,"narrative_summary":"Child must choose the right path","illustration_instructions":"Child at crossroads"},{"beat_id":"challenge_3","act":"challenge","page_index":7,"narrative_summary":"Child finds the treasure","illustration_instructions":"Child discovering treasure"},{"beat_id":"resolution_1","act":"resolution","page_index":8,"narrative_summary":"Child shares the discovery","illustration_instructions":"Child sharing with friends"},{"beat_id":"resolution_2","act":"resolution","page_index":9,"narrative_summary":"Child learns about courage","illustration_instructions":"Child proud and happy"},{"beat_id":"reflection_1","act":"reflection","page_index":10,"narrative_summary":"Child dreams of more adventures","illustration_instructions":"Child sleeping, dreaming"}]}'::jsonb
),
(
  'a0000000-0000-0000-0000-000000000003',
  'problem-solving',
  1,
  ARRAY['4-6', '7-9'],
  '{"theme":"problem-solving","supporting_characters":[{"role":"helper","description":"clever robot friend"}],"beats":[{"beat_id":"setup_1","act":"setup","page_index":1,"narrative_summary":"Child notices something is broken","illustration_instructions":"Child looking at broken item"},{"beat_id":"setup_2","act":"setup","page_index":2,"narrative_summary":"Child meets a clever helper","illustration_instructions":"Child with robot friend"},{"beat_id":"mission_1","act":"mission","page_index":3,"narrative_summary":"Together they plan the fix","illustration_instructions":"Child and helper planning"},{"beat_id":"mission_2","act":"mission","page_index":4,"narrative_summary":"Child gathers the tools","illustration_instructions":"Child collecting tools"},{"beat_id":"challenge_1","act":"challenge","page_index":5,"narrative_summary":"The first try does not work","illustration_instructions":"Child trying, puzzled"},{"beat_id":"challenge_2","act":"challenge","page_index":6,"narrative_summary":"Child thinks of a new idea","illustration_instructions":"Child having idea"},{"beat_id":"challenge_3","act":"challenge","page_index":7,"narrative_summary":"Child succeeds with teamwork","illustration_instructions":"Child and helper succeeding"},{"beat_id":"resolution_1","act":"resolution","page_index":8,"narrative_summary":"Everything works again","illustration_instructions":"Child celebrating success"},{"beat_id":"resolution_2","act":"resolution","page_index":9,"narrative_summary":"Child thanks the helper","illustration_instructions":"Child thanking friend"},{"beat_id":"reflection_1","act":"reflection","page_index":10,"narrative_summary":"Child learned that trying helps","illustration_instructions":"Child smiling, confident"}]}'::jsonb
)
ON CONFLICT (id) DO NOTHING;
