-- Dinosaur-themed template for interest matching (story personalization)
INSERT INTO public.templates (id, name, version, age_bands, config) VALUES
(
  'a0000000-0000-0000-0000-000000000004',
  'dinosaurs',
  1,
  ARRAY['4-6', '7-9'],
  '{"theme":"dinosaurs","supporting_characters":[{"role":"dino_friend","description":"friendly baby dinosaur"}],"beats":[{"beat_id":"setup_1","act":"setup","page_index":1,"narrative_summary":"Child discovers a time portal to the age of dinosaurs","illustration_instructions":"Child stepping through magical portal, dinosaur world"},{"beat_id":"setup_2","act":"setup","page_index":2,"narrative_summary":"Child meets a friendly baby dinosaur","illustration_instructions":"Child with friendly baby dinosaur"},{"beat_id":"mission_1","act":"mission","page_index":3,"narrative_summary":"The dinosaur needs help finding its family","illustration_instructions":"Child and dinosaur looking at dinosaur footprints"},{"beat_id":"mission_2","act":"mission","page_index":4,"narrative_summary":"Child and dinosaur set off on a journey","illustration_instructions":"Child walking with dinosaur through prehistoric forest"},{"beat_id":"challenge_1","act":"challenge","page_index":5,"narrative_summary":"Child spots a big dinosaur in the distance","illustration_instructions":"Child and baby dinosaur hiding behind rocks"},{"beat_id":"challenge_2","act":"challenge","page_index":6,"narrative_summary":"Child thinks of a clever way to pass safely","illustration_instructions":"Child whispering idea to dinosaur"},{"beat_id":"challenge_3","act":"challenge","page_index":7,"narrative_summary":"Child and dinosaur find the dinosaur family","illustration_instructions":"Child and baby dinosaur reunited with family"},{"beat_id":"resolution_1","act":"resolution","page_index":8,"narrative_summary":"Child says goodbye to the dinosaurs","illustration_instructions":"Child waving to dinosaur family"},{"beat_id":"resolution_2","act":"resolution","page_index":9,"narrative_summary":"Child returns through the portal","illustration_instructions":"Child stepping back through portal"},{"beat_id":"reflection_1","act":"reflection","page_index":10,"narrative_summary":"Child dreams of dinosaur adventures","illustration_instructions":"Child in bed, smiling, dinosaur toy nearby"}]}'::jsonb
)
ON CONFLICT (id) DO NOTHING;
