import { SUPPORT_EMAIL } from "@/lib/constants";

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-amber-50 px-6 py-12">
      <div className="mx-auto max-w-2xl">
        <h1 className="text-2xl font-bold text-amber-900">Privacy Policy</h1>
        <p className="mt-2 text-sm text-amber-700">Last updated: March 2026</p>

        <div className="mt-8 space-y-6 text-amber-800/90">
          <section>
            <h2 className="font-semibold text-amber-900">1. Data we collect</h2>
            <p>
              We collect: child photos you upload, answers to personalization questions (name, age,
              interests, favorites, fears to avoid), and account data (email if provided). Photos
              and answers are used only to generate your personalized storybook.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-amber-900">2. How we use your data</h2>
            <p>
              Your data is used solely to create the storybook. We do not sell or share your data
              with third parties for marketing. AI providers process data under strict no-training
              and deletion guarantees.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-amber-900">3. Storage and retention</h2>
            <p>
              Photos and generated content are stored securely. You can request deletion at any time
              via Account & Privacy. We retain data only as long as needed to deliver your book and
              comply with legal obligations.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-amber-900">4. Your rights (GDPR)</h2>
            <p>
              You have the right to access, rectify, erase, and port your data. Contact us to
              exercise these rights. We respond within 30 days.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-amber-900">5. AI disclosure</h2>
            <p>
              Story text and illustrations are generated by AI. We use your inputs to personalize
              the content. The AI does not retain your data for training.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-amber-900">6. Contact</h2>
            <p>
              For privacy requests: use the{" "}
              <a href="/account" className="text-amber-600 hover:underline">Account & Privacy</a>{" "}
              page or contact{" "}
              <a href={`mailto:${SUPPORT_EMAIL}`} className="text-amber-600 hover:underline">support</a>.
            </p>
          </section>
        </div>

        <p className="mt-12">
          <a href="/" className="text-amber-600 hover:underline">
            ← Back
          </a>
        </p>
      </div>
    </div>
  );
}
